title: DongJiahua's Homepage
page-top-title: DongJiahua
top-section-bg-text: Be what you wanna be
home-subtitle: DongJiahua&ensp;|&ensp;JL52Hertz
copyright-text: '&copy; DongJiahua 2002-11-18. All Rights Reserved.'
